### ISSUE TITLE
the sigmoid 

### ISSUE THREAD

**Issue by ladybirdhui** [Tshzzz/pytorch_yolov2#1]
hi , i have a question about the using of sigmoid
why you use sigmoid on pred_cls and pred_loc?
it seems that use sigmoid on pre_loc and pred_conf

**Comment by Tshzzz** [comment]
Sorry, my fault ! Actually I had a test with bce loss , so the pred_cls use the sigmoid . I'll fix it right away.

**Comment by ladybirdhui** [comment]
thank you
